### ISSUE TITLE
Define Scale objects

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#14]
It is currently unclear the use and storage mechanism for the `scale` of a Dataset. Determining a proper implementation of `Scale` objects may take some research.

**Comment by waxlamp** [comment]
Let's discuss this in-thread a bit, if that's ok.

@annehaley, can you give me an overview of the "scale" concept and what you're picturing it being used for? I want to make the idea more concrete so we can evaluate how soon we need to address it with a design and code, etc.

**Comment by annehaley** [comment]
As we have been slowly sculpting the concept of the Dataset model, I'm realizing the `scale` of a Dataset may simply be a numerical field, meant to aid in sorting tiles in the tile stack and relating Datasets to each other. For example, a Dataset with a scale of 1 refers to an individual, 2 refers to a population, 0.5 refers to an organ, 0.25 refers to a tissue, etc.  If we have a more robust answer to #17, we may not need to make this relationship explicit in a Dataset field, instead relating Datasets in an Investigation via some algorithm.

**Comment by waxlamp** [comment]
Ok, so in light of this I'd prefer not to tie ourselves down to a model field based solution to the problem of data scale. This is something @mcovalt has probably been thinking about in the GeoJS and tile service contexts, so I'm going to close this issue (since we haven't decided on it as the main solution) and let it be part of the general semantic zoom thinking/experimentation.
