### ISSUE TITLE
Set up a nucleus detection job type

### ISSUE THREAD

**Issue by waxlamp** [atlascope/atlascope#153]
Use HistomicsTK (perhaps running in a container) to run a job to produce a nucleus ID pixel map image. This is an image with an integer value at each pixel encoding a numeric ID for the nucleus found at that location (`0` indicates "no pixel", while positive integers indicate uniquely identified nuclei).

In case my description of the file is wrong, whatever HistomicsTK actually does is to be taken as that description instead.

@manthey will be available to help get this issue done.

**Comment by naglepuff** [comment]
https://digitalslidearchive.github.io/HistomicsTK/examples/nuclei_segmentation.html
Leaving this here for reference

**Comment by annehaley** [comment]
I wrote a job to perform nucleus detection (https://github.com/atlascope/atlascope/pull/160) and included a run of this job in the populate script. Here are some example visualizations of the output. The dataset object that is created as a result of the job does not save a preview image like these to its content. Rather, it saves only the array of detected nuclei (their centroids and bounding boxes) to the dataset metadata.Additionally, the new dataset will be of the type `nucleus_detection` instead of `analytics`. That means we can use this metadata to dynamically create these kinds of visualizations on the client side. 

![image](https://user-images.githubusercontent.com/44912689/167679404-181a78d2-d13e-4bdd-be0b-bfb01d0d2297.png)

![image](https://user-images.githubusercontent.com/44912689/167679354-287f5def-1a0b-4ac8-92e2-ece0b6e7ed2c.png)

![image](https://user-images.githubusercontent.com/44912689/167679250-510cfa11-9650-4165-b662-d463c8037e7e.png)


I had to modify some of the values in the example to fit our own sample data (`min_radius`, `max_radius`, `foreground_threshold`). Different sample data may need different values, but we can make this value-setting more robust in phase 2. For now, we can keep these hard-coded values.
