### ISSUE TITLE
Nondeterministic test results

### ISSUE THREAD

**Issue by mcovalt** [atlascope/atlascope#39]
Tests on `main` [were failing](https://github.com/atlascope/atlascope/runs/4781741058) following the merge of #33. Simply re-running the tests without changing the code-base caused tests [to succeed](https://github.com/atlascope/atlascope/runs/4781762885).

**Comment by waxlamp** [comment]
@mcovalt, are you sure the tests are actually *nondeterministic*? It could also be just weird caching issues in GitHub actions that arose upon changing the OS stack, etc.

Has this recurred since then? If not, I think we can close this and refile a more specific issue if we see flaky tests again. Let me know what you think.

**Comment by mcovalt** [comment]
> Has this recurred since then?

Yes. On #37 the same test [initially failed](https://github.com/atlascope/atlascope/runs/4795507679), but [passed on rerun](https://github.com/atlascope/atlascope/runs/4795534731).
