### ISSUE TITLE
put example data from vandy into the `populate` script

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#4]
The example data should be included as a Dataset object. This will help us determine what information we have and need to model, as well as information we lack and need to fill in.

**Comment by waxlamp** [comment]
Which component is the "dataloader"?

From this issue I can imagine one of two ways to solve it:
1. Finish the Vandy importer work, and engage it in the populate script to pull a small dataset from Vandy Explorer.
2. Download a small dataset from Vandy Explorer, and use the "upload importer" to push it into the system via the populate script.

(1) would be good because it would use a nontrivial importer; (2) would be good because it's more self-contained (doesn't rely on Vandy Explorer being there, doesn't cause any extra stress on Vandy Explorer).

(attn @marySalvi, @annehaley)

**Comment by annehaley** [comment]
The "dataloader" is a reference to the `populate` script, I had just used the "dataloader" nickname for a similar procedure on a different project and I keep calling it that. From now on, I'll refer to it as the `populate` script. Changing the name of this issue to reflect this.
