### ISSUE TITLE
Alternative to presigned URLs for images

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#59]
We decided that presigned URLs in serializers (to represent s3 file locations) are an appropriate measure for Phase 1, but they are not reliable enough for Phase 2, as presigned URLs represent temporary limited access.

**Comment by waxlamp** [comment]
Maybe presigned URLs are fine--that is the canonical way to access data in S3, and our server is essentially acting like a broker for the client to get something done in the shortest timeframe.

Otherwise, the S3 object key is maybe another option (but then the client would need to do extra work to obtain a presigned URL from that).

@dchiquito, do you have any quick advice on this topic?

**Comment by dchiquito** [comment]
I discussed this briefly with @annehaley, and IIRC there is a Django model for `JobOutputImages` that need to be serialized for rendering in the web UI. The options I can think of for serialization off the top of my head:
* A presigned URL to the image. If they are _only_ used for rendering, then it makes sense for the API to support that use case, and no others. I don't think the temporary nature is an issue, if the images are needed again then the web UI should be getting the URL again anyway.
* An object ID (UUID?). The web UI would then query a separate `/api/jobs/{job_id}/outputs/{image_id}` to get information about the image, including image URL and any metadata. This has the downside of more requests, which are slow.
* A serialization of the `JobOutputImage`, including ID, presigned image URL, and any metadata. The biggest downside I can think of is if there are truly excessive number of `JobOutputImages` to return, you might have to move this endpoint and paginate it rather than include it in a `JobSerializer`.

**Comment by waxlamp** [comment]
> * A serialization of the `JobOutputImage`, including ID, presigned image URL, and any metadata. The biggest downside I can think of is if there are truly excessive number of `JobOutputImages` to return, you might have to move this endpoint and paginate it rather than include it in a `JobSerializer`.

I don't quite understand the downside here. It doesn't seem like including more metadata would be the straw that breaks the camel's back here; even without the extra reporting, a "truly excessive number of `JobOutputImages`" would still require a paginated endpoint, right?

But, for the time being, it seems like using presigned URLs should be good enough. What do you think, @annehaley?

**Comment by annehaley** [comment]
Yes, @dchiquito's explanation helps a lot. Is the expiry of the presigned urls something we can set? If not, after what amount of time do they expire?

**Comment by waxlamp** [comment]
I think by default it's far beyond the timescale clients operate at--something like 7 days. @dchiquito could say more accurately.

**Comment by dchiquito** [comment]
The default is 1 day: https://github.com/girder/django-s3-file-field/blob/7683e9e7a07691326b131b8b478c8a51af4844a9/s3_file_field/_multipart.py#L151-L152
That number is configurable if you are using the `MultipartManager` directly, but I believe that Atlascope is not. I don't see any reason that couldn't be made a setting upstream if you need to adjust it.

**Comment by annehaley** [comment]
I believe 1 day is definitely long enough and still greater than the time scale within which the client works. Closing this issue with the resolution to keep presigned urls for now.
