### ISSUE TITLE
`DatasetEmbedding` model

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#81]
This Relationship model should allow us to specify how one Dataset is nested inside another within the context of an Investigation.

The following fields should be included: 

1. `context_investigation`
2. `parent_dataset`
3. `child_dataset`
4. `coordinates`

`coordinates` should be a JSON field which describes the coordinates of the child's upper left and lower right corners within the parent's coordinate space (in px). An example value could be as follows:
```
embedding_relationship.coordinates = [ [ 25, 25 ], [ 50, 50 ] ]
```

**Comment by waxlamp** [comment]
> This Relationship model should allow us to specify how one Dataset is nested inside another within the context of an Investigation.
> 
> The following fields should be included:
> 
> 1. `context_investigation`

If this identifies the investigation the embedding declaration belongs to, can it just be called `investigation`?

> 4. `coordinates`
> 
> `coordinates` should be a JSON field which describes the coordinates of the child's upper right and lower left corners within the parent's coordinate space (in px). An example value could be as follows:
> 
> ```
> embedding_relationship.coordinates = [ [ 25, 25 ], [ 50, 50 ] ]
> ```

The alternative would be to store a point and a scale value, depending on what makes this simpler/easier for @mcovalt.

Also, we could maybe use a [PointField](https://docs.djangoproject.com/en/3.0/ref/contrib/gis/model-api/#pointfield) to store the coordinate(s), but that depends on us using GeoDjango (@mcovalt, can you advise on this?).

Final comment: instead of `EmbeddingRelationship`, I would call this `DatasetEmbedding` or something else more direct. Everything is a relationship here, so we can spend our "word budget" on more descriptive names.

**Comment by annehaley** [comment]
The `Point` concept is a great idea, the girder cookiecutter already sets us up with a PostGIS backend. I tested it out and opened #82
